repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: VERSION|SLUG|VENDOR|REVISION|cdk.tf.json
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy
        exclude: ^gen
      - id: go-build-mod
        exclude: ^gen
      - id: go-imports
        exclude: ^gen
