---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - meh.defn.dev
  resources:
  - blargs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meh.defn.dev
  resources:
  - blargs/finalizers
  verbs:
  - update
- apiGroups:
  - meh.defn.dev
  resources:
  - blargs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meh.defn.dev
  resources:
  - hrnnggs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meh.defn.dev
  resources:
  - hrnnggs/finalizers
  verbs:
  - update
- apiGroups:
  - meh.defn.dev
  resources:
  - hrnnggs/status
  verbs:
  - get
  - patch
  - update
